version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    environment:
      PORT: 5000
      VIRTUAL_HOST: 0.0.0.0
      VIRTUAL_PORT: 5000
  nginx:
    image: jwilder/nginx-proxy:alpine
    environment:
      VIRTUAL_HOST: 0.0.0.0
      VIRTUAL_PORT: 5000
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - "4000:80"